version: "3.8"
services:
  web:
    build: .
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
            - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
        - mdb
  mdb:
    image: mysql
    container_name: mysql
    environment:
            [-MYSQL_DATABASE=mysql,
            -MYSQL_USER=mysql,
            -MYSQL_PASSWORD="Rahul@237"]
   